name: myapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  camera: ^0.9.4+19
  path_provider: ^2.0.9
  path: ^1.8.0
  arkit_plugin: ^1.0.7
  vector_math: ^2.1.4
  arcore_flutter_plugin: ^0.1.0
  flutter_unity_widget: ^2022.2.0
  image_picker: ^1.0.5
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true